language: php

php:
  - 7.4
  - 8.0
  - 8.2

before_script:
  - composer self-update
  - composer install --prefer-dist --no-interaction

script: ./vendor/bin/phpunit --coverage-clover clover.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

# Only runs tests on master or PR to master branch
branches:
  only:
    - "master"
