on:
  push:
    branches: [main]

jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: laravel-multimail
        id: first
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: ${{ secrets.CCI_TOKEN }}
